version: '3.8'
services:
  sunday-service-front:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '5173:5173'
    volumes:
      - .:/usr/src/
      - /usr/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true